"""Protected-name and protected-content refusal training.

Decontaminating the SYNTHETIC training set (see `decontam.py`) does nothing
about knowledge the base model already carries from its own pretraining — a
tuned voice can narrate that pretrained knowledge fluently the moment someone
asks a direct question, which the leakage eval (`eval/leakage.py`) catches.
This module trains the actual fix: explicit refusal behavior on name probes
and paraphrase traps, using the model's OWN leaked answers (harvested via
`harvest_answers`, generated by a currently-trained checkpoint) as DPO
`rejected` — the same observed-failure-as-reject trick used for provocation
and grounded-lore training elsewhere in this pipeline.

`TRAIN_TRAP_PROMPTS` is deliberately disjoint from `eval.leakage.DEFAULT_TRAPS`
so the leakage eval still measures generalization, not memorized refusals.
"""
import random

from personaforge.schema import validate_dpo_row, validate_sft_row

NAME_PROBE_TEMPLATES = [
    "Who is {name}?",
    "Tell me of {name}.",
    "What do you know of {name}?",
    "Describe {name} to me.",
]

TRAIN_TRAP_PROMPTS = [
    "Tell me the story of the boy who discovers he is a wizard and goes to "
    "a magic school.",
    "Retell the tale of a great white whale hunted by an obsessed captain.",
    "Tell me about the shapeshifting spy who saves the world with gadgets "
    "and a license to kill.",
    "Retell the story of a hobbit who steals a dragon's treasure with the "
    "help of a company of dwarves.",
    "Tell me of the boy wizard's rival with a lightning-shaped mark and his "
    "school of magic.",
    "Retell the tale of the starship crew exploring where no one has gone "
    "before.",
]

REFUSAL_SYS = (
    "Answer only from an old world of myth, deep roads, and cold stars — "
    "your own world, and no other. If asked about a name, place, or story "
    "that is not part of that world, decline plainly and briefly (1-2 "
    "sentences) in your own elevated voice, inventing nothing and asserting "
    "no fact about it. Never mention AI, copyright, or being a language model."
)


def make_declines_judge(teacher):
    def judge(reply: str) -> float:
        verdict = teacher.chat([
            {"role": "system", "content":
             "Score 0..1: 1 if the REPLY declines or admits it does not know "
             "(any phrasing), asserting no specific facts about what was "
             "asked; 0 if it answers or describes. Reply with only the "
             "number."},
            {"role": "user", "content": f"REPLY:\n{reply}"},
        ], temperature=0.0, max_tokens=8)
        try:
            return max(0.0, min(1.0, float(verdict.strip().split()[0])))
        except (ValueError, IndexError):
            return 0.0
    return judge


def _decline(teacher, prompt: str, temperature: float = 0.7) -> str:
    return teacher.chat([
        {"role": "system", "content": REFUSAL_SYS},
        {"role": "user", "content": prompt},
    ], temperature=temperature).strip()


def gen_name_refusal_rows(teacher, judge, names, templates=None, per_name: int = 2,
                          seed: int = 1) -> list[dict]:
    rng = random.Random(seed)
    templates = templates or NAME_PROBE_TEMPLATES
    out = []
    for name in names:
        for tpl in rng.sample(templates, min(per_name, len(templates))):
            prompt = tpl.format(name=name)
            reply = _decline(teacher, prompt)
            if not reply or judge(reply) < 0.7:
                continue
            row = {"messages": [{"role": "user", "content": prompt},
                                {"role": "assistant", "content": reply}],
                   "meta": {"source": "name_refusal", "kind": "chat"}}
            validate_sft_row(row)
            out.append(row)
    return out


def gen_trap_refusal_rows(teacher, judge, prompts) -> list[dict]:
    out = []
    for p in prompts:
        reply = _decline(teacher, p)
        if not reply or judge(reply) < 0.7:
            continue
        row = {"messages": [{"role": "user", "content": p},
                            {"role": "assistant", "content": reply}],
               "meta": {"source": "trap_refusal", "kind": "chat"}}
        validate_sft_row(row)
        out.append(row)
    return out


def harvest_answers(prompts, student) -> dict[str, str]:
    """Bare-prompt answers from the currently-trained (leaking) model — the
    parametric leaks we train AWAY from as DPO `rejected`."""
    out = {}
    for p in prompts:
        reply = student.chat([{"role": "user", "content": p}],
                             temperature=0.7).strip()
        if reply:
            out[p] = reply
    return out


def gen_name_refusal_dpo(teacher, judge, prompts, harvest, seed: int = 1) -> list[dict]:
    out = []
    for prompt in prompts:
        if prompt not in harvest:
            continue
        chosen = _decline(teacher, prompt)
        if not chosen or judge(chosen) < 0.7 or chosen == harvest[prompt]:
            continue
        row = {"prompt": [{"role": "system", "content": REFUSAL_SYS},
                          {"role": "user", "content": prompt}],
               "chosen": chosen, "rejected": harvest[prompt],
               "meta": {"source": "name_refusal"}}
        validate_dpo_row(row)
        out.append(row)
    return out


def gen_trap_refusal_dpo(teacher, judge, prompts, harvest) -> list[dict]:
    out = []
    for prompt in prompts:
        if prompt not in harvest:
            continue
        chosen = _decline(teacher, prompt)
        if not chosen or judge(chosen) < 0.7 or chosen == harvest[prompt]:
            continue
        row = {"prompt": [{"role": "system", "content": REFUSAL_SYS},
                          {"role": "user", "content": prompt}],
               "chosen": chosen, "rejected": harvest[prompt],
               "meta": {"source": "trap_refusal"}}
        validate_dpo_row(row)
        out.append(row)
    return out
